name: serasi
description: Aplikasi Administrasi

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  bloc: ^7.0.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  firebase_core: ^1.0.3
  flutter_bloc: ^7.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.3.4
  get: ^4.1.3
  google_fonts: ^2.0.0
  http: ^0.13.1
  material_design_icons_flutter: ^4.0.5955
  onesignal_flutter: ^2.6.3
  package_info: ^2.0.0
  percent_indicator: ^2.1.9
  shared_preferences: ^2.0.5
  shimmer: ^1.1.2
  supercharged: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconApp/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
